FROM docker.io/cloudflare/sandbox:0.12.9

RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="$HOME/.local/bin:$PATH"
RUN uv tool install marimo

EXPOSE 8080

# here for reference, cloudflare sandbox does not execute the CMD
CMD ["uvx", "marimo", "edit", "--host", "0.0.0.0", "--port", "8080", "--headless", "--no-token"]
